### ISSUE TITLE
Mistake in the Installation Doc

### ISSUE THREAD

**Issue by AnthonyDG** [flightphp/skeleton-simple#1]
In [README.md > Installation](https://github.com/flightphp/skeleton-simple/blob/master/README.md#installation), composer installs sketeton complex version and not the simple one :

`composer create-project flightphp/skeleton cool-project-name` 
should be 
`composer create-project flightphp/skeleton-simple cool-project-name`

It's my first days with FlightPHP and I enjoy it  :-)

**Comment by n0nag0n** [comment]
Sometimes it’s the “simple” things that get ya! This repo isn’t used as much as the other one so this little but very important mistake was overlooked. Thanks for letting me know! 

Hope you keep enjoying flight! Tell your friends!
